name: smoothie_plays_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7  
  dartz: ^0.10.1  
  http: ^1.3.0  
  shared_preferences: ^2.2.2  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  image_picker: ^1.0.4
  json_annotation: ^4.9.0 
  get_it: ^8.0.3
  mocktail: ^1.0.4

dev_dependencies:
  analyzer: ^6.11.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/
    - assets/images/defaultphoto.jpg
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-Italic.ttf
          weight: 300